ARG DEPS_IMAGE
FROM ${DEPS_IMAGE}

COPY . .

RUN pytest && rm -r .pytest_cache

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]