FROM mlproject_base:latest

COPY . .

RUN pytest && rm -r .pytest_cache

EXPOSE 8000

HEALTHCHECK CMD curl --fail http://localhost:8000/

ENTRYPOINT ["uvicorn", "main_fast_api:app", "--host", "0.0.0.0", "--port", "8000"]