name: Build docker image and deploy to server

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login into docker hub
      run: docker login -u urfu_mlproject -p "glpat-_f6MA6s1CZwSk2-xPSHP" registry.gitlab.com
    - name: Build the Docker base image
      run: docker build . --file Dockerfile_base --tag mlproject_base:latest
    - name: Build the Docker fastapi image
      run: docker build . --file Dockerfile_fastapi --tag registry.gitlab.com/djvue/urfu-deployments/mlproject-fastapi:${{ github.ref_name }}
    - name: Push the Docker fastapi image
      run: docker push registry.gitlab.com/djvue/urfu-deployments/mlproject-fastapi:${{ github.ref_name }}
    - name: Build the Docker streamlit image
      run: docker build . --file Dockerfile_streamlit --tag registry.gitlab.com/djvue/urfu-deployments/mlproject-streamlit:${{ github.ref_name }}
    - name: Push the Docker fastapi image
      run: docker push registry.gitlab.com/djvue/urfu-deployments/mlproject-streamlit:${{ github.ref_name }}

  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Set target
      run: export target=deploy_m1
    - name: Set tags
      run: export tags=all
    - name: Set tags
      run: export project_id=52282824
    - name: Debug variables
      run: echo "target=$target tags=$tags project_id=$project_id"
    - name: Run deploy pipeline, see https://gitlab.com/djvue/urfu-deployments/-/pipelines
      run: |
        curl --request POST \
              --form "token=$CI_JOB_TOKEN" \
              --form ref=master \
              --form "variables[target]=$target" \
              --form "variables[image_tag]=$image_tag" \
              --form "variables[tags]=$tags" \
              "https://gitlab.com/api/v4/projects/$JOBS_PROJECT_ID/trigger/pipeline"