name: Build docker image and deploy to server

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      docker_registry_user: ${{ secrets.CI_REGISTRY_USER }}
      docker_registry_password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      image_base_prefix: djvue/urfu-deployments:streamlit-mlproject-base
      image_streamlit: djvue/urfu-deployments:streamlit-mlproject-streamlit-${{ github.ref_name }}
      image_fastapi: djvue/urfu-deployments:streamlit-mlproject-fastapi-${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v2
    - name: Set base image hash
      run: echo "deps_hash=$(cat requirements.txt | md5sum | awk '{print $1}')" >> $GITHUB_ENV
    - name: Set base image
      run: echo "image_base=$image_base_prefix-$deps_hash" >> $GITHUB_ENV
    - name: Login into docker hub
      run: docker login -u $docker_registry_user -p "$docker_registry_password"
    - name: Build the Docker base image
      run: |
        docker pull $image_base || (\
          docker build . --file Dockerfile_base --tag $image_base \
          && docker push $image_base \
        )
    - name: Build the Docker streamlit image
      run: docker build . --file Dockerfile_streamlit --build-arg DEPS_IMAGE=$image_base --tag $image_streamlit
    - name: Build the Docker fastapi image
      run: docker build . --file Dockerfile_fastapi --build-arg DEPS_IMAGE=$image_base --tag $image_fastapi
    - name: Push the Docker streamlit image
      run: docker push $image_streamlit
    - name: Push the Docker fastapi image
      run: docker push $image_fastapi

  deploy:
    name: Deploy to prod host
    needs: build
    runs-on: ubuntu-latest
    env:
      PACKAGES_TO_UPGRADE: ${{ needs.run_publish.outputs.packages }}
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}

      event_type: deploy_ml1
      ansible_tags: all
      image_tag: ${{ github.ref_name }}

    strategy:
      matrix:
        repo: ['djvue/urfu-deployments']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $DISPATCH_TOKEN" \
            --request POST \
            --data "{\"event_type\": \"$event_type\", \"client_payload\": { \"ansible_tags\": \"$ansible_tags\", \"image_tag\": \"$image_tag\" }}" \
            https://api.github.com/repos/${{ matrix.repo }}/dispatches